// 简化国家列表(中英对照),节点 31/33/34/35 用 country-select 引用。
// 列表覆盖 B2B 钢材/工业品常见出口目的地;不全的部分用户可在节点 31 备注里手填。

export const COUNTRIES = [
    { code: 'US', zh: '美国', en: 'United States' },
    { code: 'CA', zh: '加拿大', en: 'Canada' },
    { code: 'MX', zh: '墨西哥', en: 'Mexico' },
    { code: 'BR', zh: '巴西', en: 'Brazil' },
    { code: 'AR', zh: '阿根廷', en: 'Argentina' },
    { code: 'CL', zh: '智利', en: 'Chile' },
    { code: 'CO', zh: '哥伦比亚', en: 'Colombia' },
    { code: 'PE', zh: '秘鲁', en: 'Peru' },
    { code: 'GB', zh: '英国', en: 'United Kingdom' },
    { code: 'DE', zh: '德国', en: 'Germany' },
    { code: 'FR', zh: '法国', en: 'France' },
    { code: 'IT', zh: '意大利', en: 'Italy' },
    { code: 'ES', zh: '西班牙', en: 'Spain' },
    { code: 'NL', zh: '荷兰', en: 'Netherlands' },
    { code: 'BE', zh: '比利时', en: 'Belgium' },
    { code: 'PL', zh: '波兰', en: 'Poland' },
    { code: 'SE', zh: '瑞典', en: 'Sweden' },
    { code: 'NO', zh: '挪威', en: 'Norway' },
    { code: 'DK', zh: '丹麦', en: 'Denmark' },
    { code: 'FI', zh: '芬兰', en: 'Finland' },
    { code: 'GR', zh: '希腊', en: 'Greece' },
    { code: 'PT', zh: '葡萄牙', en: 'Portugal' },
    { code: 'CH', zh: '瑞士', en: 'Switzerland' },
    { code: 'AT', zh: '奥地利', en: 'Austria' },
    { code: 'IE', zh: '爱尔兰', en: 'Ireland' },
    { code: 'CZ', zh: '捷克', en: 'Czech Republic' },
    { code: 'HU', zh: '匈牙利', en: 'Hungary' },
    { code: 'RO', zh: '罗马尼亚', en: 'Romania' },
    { code: 'TR', zh: '土耳其', en: 'Turkey' },
    { code: 'RU', zh: '俄罗斯', en: 'Russia' },
    { code: 'UA', zh: '乌克兰', en: 'Ukraine' },
    { code: 'KZ', zh: '哈萨克斯坦', en: 'Kazakhstan' },
    { code: 'AE', zh: '阿联酋', en: 'United Arab Emirates' },
    { code: 'SA', zh: '沙特阿拉伯', en: 'Saudi Arabia' },
    { code: 'QA', zh: '卡塔尔', en: 'Qatar' },
    { code: 'KW', zh: '科威特', en: 'Kuwait' },
    { code: 'OM', zh: '阿曼', en: 'Oman' },
    { code: 'IL', zh: '以色列', en: 'Israel' },
    { code: 'IR', zh: '伊朗', en: 'Iran' },
    { code: 'IQ', zh: '伊拉克', en: 'Iraq' },
    { code: 'EG', zh: '埃及', en: 'Egypt' },
    { code: 'ZA', zh: '南非', en: 'South Africa' },
    { code: 'NG', zh: '尼日利亚', en: 'Nigeria' },
    { code: 'KE', zh: '肯尼亚', en: 'Kenya' },
    { code: 'MA', zh: '摩洛哥', en: 'Morocco' },
    { code: 'IN', zh: '印度', en: 'India' },
    { code: 'PK', zh: '巴基斯坦', en: 'Pakistan' },
    { code: 'BD', zh: '孟加拉国', en: 'Bangladesh' },
    { code: 'LK', zh: '斯里兰卡', en: 'Sri Lanka' },
    { code: 'JP', zh: '日本', en: 'Japan' },
    { code: 'KR', zh: '韩国', en: 'South Korea' },
    { code: 'TH', zh: '泰国', en: 'Thailand' },
    { code: 'VN', zh: '越南', en: 'Vietnam' },
    { code: 'MY', zh: '马来西亚', en: 'Malaysia' },
    { code: 'SG', zh: '新加坡', en: 'Singapore' },
    { code: 'ID', zh: '印度尼西亚', en: 'Indonesia' },
    { code: 'PH', zh: '菲律宾', en: 'Philippines' },
    { code: 'MM', zh: '缅甸', en: 'Myanmar' },
    { code: 'KH', zh: '柬埔寨', en: 'Cambodia' },
    { code: 'AU', zh: '澳大利亚', en: 'Australia' },
    { code: 'NZ', zh: '新西兰', en: 'New Zealand' },
];
