// 44 节点完整字段 schema(按客户《前期立项表_修改意见》重排)。
// 一份 schema 同时驱动:表单渲染 / 校验 / 联动 / Markdown 输出 / ZIP 归档。
// 字段索引规则:`node{原节点排序}_{语义短名}`,与用户字段表节点排序一致。
// 阶段:1 身份 / 2 规模 / 3 市场 / 4 产能 / 5 品质 / 6 拍摄 / 7 联络

export const FIELDS = [
    // ============ 阶段一:企业身份识别 ============
    {
        id: 'node1_companyNameZh',
        stage: 1, order: 1,
        label: '公司中文名称',
        component: 'text',
        placeholder: '例:广东xxxx有限公司(与营业执照完全一致)',
        pdfSection: 'identity', pdfKey: 'companyZh',
    },
    {
        id: 'node2_companyNameEn',
        stage: 1, order: 2,
        label: '公司英文名称',
        component: 'text',
        placeholder: '例:Guangdong xxxx Co., Ltd.',
        pdfSection: 'identity', pdfKey: 'companyEn',
    },
    {
        id: 'node3_brands',
        stage: 1, order: 3,
        label: '品牌名称(英文)',
        component: 'dynamic-list',
        itemLabel: '品牌',
        addLabel: '+ 添加备用品牌',
        itemField: { type: 'text' },
        placeholder: '例:CHUANGRUI / T-CHEF',
        pdfSection: 'identity',
    },
    {
        id: 'node4_brandLogo',
        stage: 1, order: 4,
        label: '品牌 Logo',
        component: 'file',
        accept: ['ai', 'svg', 'png', 'jpg'],
        maxSize: 10 * 1024 * 1024,
        help: '上传公司的对外 logo,如没有无需上传(透明背景矢量优先)',
        pdfSection: 'identity',
    },
    {
        id: 'node4_brandColor',
        stage: 1, order: 5,
        label: '品牌主色',
        component: 'color',
        help: '产品主色系(您期望呈现的品牌色调),用于片头片尾、字幕条配色',
        pdfSection: 'identity',
    },
    {
        id: 'node5_foundedYear',
        stage: 1, order: 6,
        label: '工厂成立年份',
        component: 'year',
        pdfSection: 'identity', pdfKey: 'foundedYear',
    },
    {
        id: 'node8_address',
        stage: 1, order: 7,
        label: '可供上门拍摄的地址',
        component: 'dynamic-card',
        cardTemplate: [
            { id: 'areaName', label: '区域名称/用途', type: 'text',
              placeholder: '如: 生产区域 / 仓库' },
            { id: 'addressDetail', label: '完整详细地址', type: 'text',
              placeholder: '请完整填写省、市、区、街道、工业园及门牌号' },
        ],
        help: '请填写可供团队上门拍摄的准确地址。如有多个拍摄地(例如:生产车间与仓库不在同一处),请点击下方按钮新增地址。',
        pdfSection: 'identity',
    },
    {
        id: 'node5_companyIntro',
        stage: 1, order: 8,
        label: '公司简介',
        component: 'textarea',
        placeholder: '请用一段精炼的文字介绍您的公司。如: 成立于哪年、主打什么产品、有什么核心优势或行业地位',
        help: '这段简介将主要用于置顶视频的文案撰写,按照独立站官网/阿里国际站简介的公司介绍格式进行填写。',
        pdfSection: 'identity',
    },

    // ============ 阶段二:规模与资质实力 ============
    {
        id: 'node9_employeeCount',
        stage: 2, order: 9,
        label: '人员规模',
        component: 'text',
        placeholder: '例:1-50 / 51-200 / 201-500 / 501-1000 / 1000+',
        help: '请填写工厂大致人数',
        pdfSection: 'scale',
    },
    {
        id: 'node11_plant',
        stage: 2, order: 10,
        label: '厂房面积',
        component: 'composite',
        subFields: [
            { id: 'area', label: '面积/㎡', type: 'number' },
            { id: 'aerialPhotos', label: '厂房航拍/外景图/工厂大门', type: 'file', multiple: true,
              accept: ['jpg', 'png', 'mp4'], maxSize: 30 * 1024 * 1024 },
        ],
        help: '作为航拍镜头与立项规模印证,请填写工厂平方数',
        pdfSection: 'scale',
    },
    {
        id: 'node12_honors',
        stage: 2, order: 11,
        label: '政府认定与行业荣誉',
        component: 'dynamic-card',
        cardTemplate: [
            { id: 'name', label: '荣誉名称', type: 'text',
              placeholder: '如: 国家高新技术企业 / 专精特新 / 省级出口优秀' },
            { id: 'file', label: '证书扫描件', type: 'file',
              accept: ['pdf', 'jpg', 'png'], maxSize: 10 * 1024 * 1024 },
        ],
        help: '无则跳过;有则每项需附扫描件,后期可作为视频素材',
        pdfSection: 'qualifications',
    },
    {
        id: 'node13_certifications',
        stage: 2, order: 12,
        label: '企业资质与产品认证',
        component: 'dynamic-card',
        cardTemplate: [
            { id: 'name', label: '资质/认证名称', type: 'text',
              placeholder: '如: ISO9001 / CE / RoHS / FCC / FDA' },
            { id: 'file', label: '证书扫描件上传', type: 'file',
              accept: ['pdf', 'jpg', 'png'], maxSize: 10 * 1024 * 1024 },
        ],
        help: '无则跳过;有则每项需附扫描件,后期可作为视频素材',
        pdfSection: 'qualifications',
    },
    {
        id: 'node14_audits',
        stage: 2, order: 13,
        label: '是否有品牌授权及大牌合作代工',
        component: 'dynamic-card',
        cardTemplate: [
            { id: 'name', label: '授权品牌名称', type: 'text',
              placeholder: '如: 沃尔玛 / 迪士尼 / 亚马逊 / Costco' },
            { id: 'file', label: '报告/授权书扫描件', type: 'file',
              accept: ['pdf', 'jpg', 'png'], maxSize: 20 * 1024 * 1024 },
        ],
        help: '无则跳过;如有填写默认征得品牌同意',
        pdfSection: 'qualifications',
    },

    // ============ 阶段三:市场与客户背景 ============
    {
        id: 'node15_categories',
        stage: 3, order: 14,
        label: '主营产品类目',
        component: 'dynamic-list',
        itemLabel: '类目路径',
        addLabel: '+ 添加主营类目',
        itemField: { type: 'text' },
        placeholder: '',
        help: '填写格式参照阿里国际站的产品类别如:五金工具-手动工具-扳手;如有多个主营类目请分别添加',
        pdfSection: 'market',
    },
    {
        id: 'node16_hsCodes',
        stage: 3, order: 15,
        label: '海关 HS 编码',
        component: 'dynamic-card',
        cardTemplate: [
            { id: 'code', label: '申报海关的 HS 编码', type: 'text' },
            { id: 'productName', label: '对应产品中文名', type: 'text' },
            { id: 'productPhoto', label: '对应产品图片', type: 'file',
              accept: ['jpg', 'png'], maxSize: 20 * 1024 * 1024 },
            { id: 'isMain', label: '是否主推', type: 'switch' },
        ],
        help: '重要:用于广告投放筛选目标国家,如不清楚海关编码,请打开网址查询。海关编码查询:https://www.hsbianma.com/search?keywords=',
        pdfSection: 'market',
    },
    {
        id: 'node17_catalog',
        stage: 3, order: 16,
        label: '产品电子图册(Catalog)',
        component: 'file',
        multiple: true,
        accept: ['pdf'],
        maxSize: 50 * 1024 * 1024,
        help: '完整产品手册 PDF;如有多套(中/英/分系列)请分别上传',
        pdfSection: 'market',
    },
    {
        id: 'node18_heroProducts',
        stage: 3, order: 17,
        label: '核心爆款/主推产品(3-5 款)',
        component: 'dynamic-card',
        cardTemplate: [
            { id: 'nameZh', label: '产品中文名', type: 'text' },
            { id: 'nameEn', label: '产品英文名', type: 'text' },
            { id: 'model', label: '型号', type: 'text' },
            { id: 'specs', label: '关键参数及材质', type: 'textarea',
              placeholder: '例如产品材质及质量参数;请务必写出当前产品的核心材质及用料' },
            { id: 'competitiveness', label: '产品竞争力', type: 'textarea',
              placeholder: '如该产品有竞争力,请告知核心亮点(如: 独家专利设计、极低返修率、特殊工艺等)' },
            { id: 'priceRange', label: '价格区间/元', type: 'text',
              placeholder: '例: 10 - 50' },
            { id: 'moq', label: '起订量', type: 'text',
              placeholder: '例: 100 pcs / 5 套' },
            { id: 'productPhoto', label: '产品图片', type: 'file',
              accept: ['jpg', 'png'], maxSize: 20 * 1024 * 1024 },
            { id: 'mainMarket', label: '主推市场区域', type: 'text',
              placeholder: '北美 / 欧洲 / 中东 / 东南亚 / 南美 / 非洲 / 澳新' },
        ],
        pdfSection: 'market',
    },
    {
        id: 'node30_keywords',
        stage: 3, order: 18,
        label: '行业关键词清单',
        component: 'composite',
        subFields: [
            { id: 'zh', label: '中文关键词', type: 'text',
              placeholder: '请在此输入多个关键词,单词之间请用英文逗号(,)或空格隔开' },
            { id: 'en', label: '英文关键词', type: 'text',
              placeholder: '请在此输入多个关键词,单词之间请用英文逗号(,)或空格隔开' },
        ],
        pdfSection: 'market',
    },
    {
        id: 'node31_blacklist',
        stage: 3, order: 19,
        label: '不接单区域(黑名单)',
        component: 'dynamic-card',
        cardTemplate: [
            { id: 'country', label: '国家/地区', type: 'country-select' },
            { id: 'reason', label: '原因', type: 'text',
              placeholder: '合规 / 物流 / 无认证 / 历史坏账 / 其他' },
            { id: 'note', label: '备注', type: 'text' },
        ],
        help: '您不想开发的市场,或者产品不适应的市场,请告知,规避投放',
        pdfSection: 'market',
    },
    {
        id: 'node32_domesticCompetitors',
        stage: 3, order: 20,
        label: '国内同行业竞争对手',
        component: 'dynamic-card',
        cardTemplate: [
            { id: 'name', label: '公司名称', type: 'text' },
            { id: 'brand', label: '品牌', type: 'text' },
            { id: 'website', label: '官网 URL', type: 'url' },
            { id: 'social', label: '社媒账号链接', type: 'tag-input',
              placeholder: '添加 FB / IG / LinkedIn 链接' },
        ],
        help: '作为参考,研究竞对流量来源',
        pdfSection: 'market',
    },
    {
        id: 'node33_overseasCompetitors',
        stage: 3, order: 21,
        label: '国外同行业竞争对手',
        component: 'dynamic-card',
        cardTemplate: [
            { id: 'name', label: '公司名称', type: 'text' },
            { id: 'country', label: '所在国家', type: 'country-select' },
            { id: 'website', label: '官网 URL', type: 'url' },
            { id: 'social', label: '海外社媒账号', type: 'tag-input',
              placeholder: '添加 FB / IG / YouTube / LinkedIn' },
        ],
        help: '作为参考,研究竞对流量来源',
        pdfSection: 'market',
    },
    {
        id: 'node34_customerCases',
        stage: 3, order: 22,
        label: '海外客户落地案例',
        component: 'dynamic-card',
        cardTemplate: [
            { id: 'country', label: '客户所在国', type: 'country-select' },
            { id: 'type', label: '客户类型', type: 'text',
              placeholder: '贸易商 / 品牌商 / 工厂' },
            { id: 'years', label: '合作年限', type: 'number' },
            { id: 'scenario', label: '典型订单场景', type: 'textarea' },
            { id: 'authorized', label: '是否可授权使用 LOGO/照片', type: 'text',
              placeholder: '是 / 否' },
            { id: 'photos', label: '现场照片', type: 'file', multiple: true,
              accept: ['jpg', 'png'], maxSize: 20 * 1024 * 1024 },
        ],
        help: '方便在目标市场投放时插入成功案例素材',
        pdfSection: 'market',
    },
    {
        id: 'node35_testimonials',
        stage: 3, order: 23,
        label: '高频复购原因与客户证言',
        component: 'dynamic-card',
        cardTemplate: [
            { id: 'quote', label: '客户好评原话或简单说明', type: 'textarea',
              placeholder: '可直接复制客户的评价,或简要说明(如:中东客户夸赞我们交期快、品质稳定)' },
            { id: 'screenshot', label: '好评/聊天/邮件截图', type: 'file',
              accept: ['jpg', 'png'], maxSize: 20 * 1024 * 1024 },
        ],
        help: '截图是视频中论证信任感最直接的画面素材。客户可以直接上传好评截图,并附上简要说明。',
        pdfSection: 'market',
    },
    {
        id: 'node37_misconceptions',
        stage: 3, order: 24,
        label: '买家常有的误区与事实真相',
        component: 'dynamic-card',
        cardTemplate: [
            { id: 'misunderstanding', label: '买家通常以为是怎样的?(常犯的误区)', type: 'textarea',
              placeholder: '请用大白话填写。如:买家以为全球都用和国内一样的直冲马桶;' },
            { id: 'truth', label: '但实际真相/我们是怎么专业解决的?', type: 'textarea',
              placeholder: '请用大白话填写。如:其实北美只认虹吸式马桶,我们发往北美的货 100% 是虹吸的;' },
        ],
        help: '填这一题,是为了在视频里跟客户"科普",展示咱们厂比同行更专业、更懂行。把客户容易想错、搞错的事情写下来,并说说咱们是怎么专业解决的。',
        pdfSection: 'market',
    },
    {
        id: 'node38_audience',
        stage: 3, order: 25,
        label: '目标客户画像与反向排雷',
        component: 'dynamic-card',
        cardTemplate: [
            { id: 'idealType', label: '理想买家类型', type: 'text',
              placeholder: '如: 批发商 / 品牌商 / 连锁商 / 跨境电商大卖家 / 工程项目商' },
            { id: 'idealVolume', label: '采购量级需求', type: 'text',
              placeholder: '如: 年采购额 50 万+ USD / 单笔 5 万 USD 以上' },
            { id: 'idealRole', label: '目标决策人角色', type: 'text',
              placeholder: '如: 采购总监 / 创始人 / 研发工程师 / 产品经理' },
            { id: 'unwanted', label: '不理想客户(反向排雷)', type: 'textarea',
              placeholder: '如: 贸易中介 / 单次低于最小起订量的零售试单 / 只要超低价的 C 端卖家' },
        ],
        help: '支持添加多组客户画像。如果您的工厂面对不同的市场或产品线有不同的目标客群,可以通过点击下方"新增"按钮进行分组补充。',
        pdfSection: 'market',
    },

    // ============ 阶段四:生产能力画像 ============
    {
        id: 'node20_productionProcess',
        stage: 4, order: 26,
        label: '产品生产工序与流程节点',
        component: 'textarea',
        placeholder: '请按先后顺序填写产品从原料到成品的完整生产节点。例如:鞋材行业的示例:原料配混 → 注塑/发泡成型 → 鞋底鞋面组合 → 去边修整 → 表面装饰 → 定型 → 质量检验 → 包装入库',
        help: '请列出核心生产步骤。这不仅能展示工厂的完整制造能力,还能直接帮助摄制组规划生产车间的拍摄动线与画面流转顺序。',
        pdfSection: 'capacity',
    },
    {
        id: 'node19_productionLines',
        stage: 4, order: 27,
        label: '核心生产设备与对应流程',
        component: 'dynamic-card',
        cardTemplate: [
            { id: 'processNode', label: '对应生产流程', type: 'text',
              placeholder: '如: 注塑 / 鞋面与鞋底组合 / 装饰与表面处理' },
            { id: 'machineName', label: '对应机器名称', type: 'text',
              placeholder: '如: EVA 全自动发泡成型机 / 自动刷胶压底流水线 / 冷热定型机' },
            { id: 'count', label: '数量', type: 'text',
              placeholder: '如: 10 台 / 3 条自动线' },
            { id: 'highlights', label: '机器亮点/优势', type: 'textarea',
              placeholder: '如: 双色注塑一次成型,零废料边角;或 全自动精准刷胶,有效杜绝溢胶和开胶现象' },
            { id: 'machinePhoto', label: '对应机器照片', type: 'file',
              accept: ['jpg', 'png'], maxSize: 20 * 1024 * 1024 },
        ],
        help: '请列出各生产环节中的核心机器设备(可点击下方按钮新增多组)。这些"硬实力"设备及其亮点,将是视频车间取景阶段最重要的拍摄目标。',
        pdfSection: 'capacity',
    },
    {
        id: 'node23_customization',
        stage: 4, order: 28,
        label: '定制服务能力(OEM/ODM)',
        component: 'composite',
        subFields: [
            { id: 'enabled', label: '是否提供定制', type: 'switch' },
            { id: 'types', label: '定制类型', type: 'text',
              placeholder: '如: OEM / ODM / JDM / OBM',
              showWhen: { field: 'enabled', equals: true } },
            { id: 'leadTime', label: '定制周期', type: 'text',
              placeholder: '≤7 天 / 8-15 天 / 16-30 天 / 30 天+',
              showWhen: { field: 'enabled', equals: true } },
            { id: 'process', label: '定制流程描述', type: 'textarea',
              placeholder: '如:打样→确认→量产',
              showWhen: { field: 'enabled', equals: true } },
            { id: 'minMoq', label: '最小定制起订量', type: 'text',
              showWhen: { field: 'enabled', equals: true } },
        ],
        pdfSection: 'capacity',
    },

    // ============ 阶段五:品质与合规体系 ============
    {
        id: 'node24_qcWorkflow',
        stage: 5, order: 29,
        label: '质量管控体系(QC 流程与检测)',
        component: 'dynamic-card',
        cardTemplate: [
            { id: 'testName', label: '测试/质检项目名称', type: 'text',
              placeholder: '如: IQC 进料检验 / 盐雾测试 96h / 成品可靠性测试' },
            { id: 'testPhoto', label: '对应检测过程或设备照片', type: 'file',
              accept: ['jpg', 'png'], maxSize: 20 * 1024 * 1024 },
        ],
        help: '填写工厂具体实施的检测/测试项目,并上传对应的实验室设备或质检现场照片。这在视频脚本中是极为具说服力的"品质控制"画面源。',
        pdfSection: 'quality',
    },
    {
        id: 'node24_rdPersonnel',
        stage: 5, order: 30,
        label: '研发团队总人数',
        component: 'text',
        placeholder: '如: 15 人 (包含工程师、设计师等)',
        help: '研发人员的规模是展现工厂创新软实力的重要数据。',
        pdfSection: 'quality',
    },
    {
        id: 'node24_patents',
        stage: 5, order: 31,
        label: '授权专利明细',
        component: 'dynamic-card',
        cardTemplate: [
            { id: 'patentType', label: '资质类型', type: 'text',
              placeholder: '实用新型 / 发明公布 / 发明授权 / 外观设计 / 国际专利' },
            { id: 'patentName', label: '资质名称', type: 'text',
              placeholder: '如: 一种新型防滑减震鞋底结构' },
            { id: 'patentFile', label: '资质上传', type: 'file',
              accept: ['pdf', 'jpg', 'png'], maxSize: 20 * 1024 * 1024 },
        ],
        help: '请点击下方按钮逐个新增您拥有的授权专利。专利证书是技术壁垒和研发实力的最直观体现。',
        pdfSection: 'quality',
    },
    {
        id: 'node25_moq',
        stage: 5, order: 32,
        label: '起订量门槛(MOQ)',
        component: 'dynamic-card',
        cardTemplate: [
            { id: 'category', label: '产品类别', type: 'text' },
            { id: 'qty', label: 'MOQ 数量', type: 'number' },
            { id: 'unit', label: '单位', type: 'text', placeholder: 'pcs / sets / tons / 卷' },
            { id: 'note', label: '备注', type: 'text',
              placeholder: '如:可议 / 约 5 吨' },
        ],
        pdfSection: 'quality',
    },
    {
        id: 'node26_leadTime',
        stage: 5, order: 33,
        label: '交货周期(Lead Time)',
        component: 'composite',
        subFields: [
            { id: 'batch', label: '批量单平均天数', type: 'number' },
            { id: 'custom', label: '定制单平均天数', type: 'number' },
            { id: 'note', label: '备注(旺季加几天等)', type: 'text' },
        ],
        pdfSection: 'quality',
    },
    {
        id: 'node27_samplePolicy',
        stage: 5, order: 34,
        label: '样品政策',
        component: 'composite',
        subFields: [
            { id: 'cost', label: '样品费', type: 'text',
              placeholder: '免费 / 收费 / 下单抵扣' },
            { id: 'freight', label: '运费', type: 'text',
              placeholder: '买家付 / 卖家付 / 到付' },
            { id: 'amountUsd', label: '典型样品费(USD)', type: 'number' },
        ],
        pdfSection: 'quality',
    },
    {
        id: 'node28_workflow',
        stage: 5, order: 35,
        label: '企业内部业务流转',
        component: 'sortable-list',
        defaultItems: ['需求', '设计', '生产', '检测', '交付', '售后'],
        editable: true,
        help: '直接驱动后续【生产流程↔取景区域】联动',
        pdfSection: 'quality',
    },
    {
        id: 'node36_afterSales',
        stage: 5, order: 36,
        label: '售后保障服务',
        component: 'textarea',
        placeholder: '请在此详细输入您提供的售后保障服务内容。例如:\n1. 质保服务:提供 X 年质保服务\n2. 零配件:免费提供核心备件\n3. 技术支持:提供 1 对 1 24 小时在线技术支持或视频教学指导\n4. 其他:支持海外仓换货等',
        pdfSection: 'quality',
    },

    // ============ 阶段六:拍摄执行筹备 ============
    {
        id: 'node39_onCameraPeople',
        stage: 6, order: 37,
        label: '出镜人员筹备',
        component: 'dynamic-card',
        cardTemplate: [
            { id: 'name', label: '姓名', type: 'text' },
            { id: 'title', label: '职位', type: 'text' },
            { id: 'isFounder', label: '是否老板/创始人', type: 'switch' },
            { id: 'english', label: '是否能英文发言', type: 'text',
              placeholder: '流利 / 基本可以 / 不可以' },
            { id: 'willing', label: '上镜意愿', type: 'text',
              placeholder: '必出镜 / 可出镜 / 拒绝' },
        ],
        help: '至少 1 人愿意出镜;明确老板/创始人 — 信任背书最强镜头',
        pdfSection: 'shooting',
    },
    {
        id: 'node40_locations',
        stage: 6, order: 38,
        label: '核心取景区域及可拍摄清单',
        component: 'dynamic-card',
        cardTemplate: [
            { id: 'name', label: '可拍摄区域/地点名称', type: 'text',
              placeholder: '请模拟客户来访动线依次填写,如: 工厂大门、生产车间-模具区域、生产车间-注塑区域、生产车间-检测区域、办公室、展厅....' },
            { id: 'photos', label: '区域参考照片', type: 'file', multiple: true,
              accept: ['jpg', 'png'], maxSize: 20 * 1024 * 1024 },
            { id: 'shotDetail', label: '可拍摄画面与细节描述', type: 'textarea',
              placeholder: '如: 拍摄机械臂自动抓取特写;拍摄原料整齐堆放的广角镜头,体现库存充足' },
        ],
        help: '请模拟客户来访从工厂大门出发的真实路线,依次添加所有允许拍摄的区域。并请尽可能详细地描述该区域内有哪些值得拍摄的设备、操作或流程。',
        pdfSection: 'shooting',
    },
    {
        id: 'node41_highlightShots',
        stage: 6, order: 39,
        label: '重点突出的高光镜头建议',
        component: 'dynamic-card',
        cardTemplate: [
            { id: 'linkedLocation', label: '关联取景区域', type: 'text',
              placeholder: '请直接输入上一题中您填写的地点名称,如: 生产车间-注塑区域' },
            { id: 'description', label: '高光镜头画面方案', type: 'textarea',
              placeholder: '如: 突出 xx 型号自动化线高速运转特写,体现高速生产的硬实力' },
            { id: 'linkedPains', label: '解决的客户痛点/疑虑', type: 'text',
              placeholder: '如: 打消买家对"小厂组装、制造设备落后"的顾虑' },
        ],
        help: '高光镜头是视频开篇黄金 3 秒或核心展示段的视觉抓手。请结合上题填写的物理取景区域,写出最能打动海外买家的特写或画面方案。',
        pdfSection: 'shooting',
    },
    {
        id: 'node42_existingAssets',
        stage: 6, order: 40,
        label: '现有素材库上传',
        component: 'dynamic-card',
        cardTemplate: [
            { id: 'type', label: '素材类型', type: 'text',
              placeholder: '视频 / 白底图 / 场景图 / 展会照 / 客户来访照 / 暂无' },
            { id: 'count', label: '数量', type: 'number' },
            { id: 'link', label: '云盘链接', type: 'url' },
            { id: 'extractCode', label: '提取码', type: 'text' },
            { id: 'authScope', label: '授权范围', type: 'multi-select',
              options: ['FB', 'IG', 'YouTube', '官网'] },
        ],
        pdfSection: 'shooting',
    },
    {
        id: 'node43_noShootZones',
        stage: 6, order: 41,
        label: '保密限制与禁拍区域',
        component: 'composite',
        subFields: [
            { id: 'warning', label: '保密事项(红字警示)', type: 'textarea',
              placeholder: '如:客户 LOGO 区 / 某型号模具 / 财务办公区' },
            { id: 'forbiddenLocations', label: '禁拍区域', type: 'tag-input',
              placeholder: '回车添加,引用"取景区域"中的名称' },
            { id: 'ndaFile', label: '保密协议(如需签署)', type: 'file',
              accept: ['pdf'], maxSize: 10 * 1024 * 1024 },
        ],
        pdfSection: 'shooting',
    },
    {
        id: 'node44_shootingSchedule',
        stage: 6, order: 42,
        label: '成品/制品生产镜头规划',
        component: 'dynamic-card',
        cardTemplate: [
            { id: 'productName', label: '可拍摄生产过程的主推产品名称', type: 'text',
              placeholder: '如: 智能扫地机器人 / 精密五金齿轮' },
            { id: 'shootLocation', label: '拍摄区域/车间工位', type: 'text',
              placeholder: '如: 3 号组装车间、包装生产线末端' },
            { id: 'shootMachine', label: '生产/加工机器设备名称', type: 'text',
              placeholder: '如: 激光镭雕打标机、全自动高速封口包装机' },
            { id: 'shotDetail', label: '画面动作描述(特写建议)', type: 'text',
              placeholder: '如: 拍摄刚组装完的成品从传送带源源不断流出;或机械臂精准抓取装箱' },
        ],
        help: '请列出可拍摄完整生产过程的主推产品(支持点击下方按钮新增多组)。成品成型与流水线下线是工厂视频中极其重要的"高光视觉镜头",提前明确机器与位置能让团队高效捕捉。',
        pdfSection: 'shooting',
    },

    // ============ 阶段七:联络与数字化触点 ============
    {
        id: 'node46_platforms',
        stage: 7, order: 43,
        label: '现有电商/官网矩阵',
        component: 'dynamic-card',
        cardTemplate: [
            { id: 'platform', label: '平台', type: 'text',
              placeholder: '独立站 / Alibaba / Made-in-China / Global Sources / Amazon / 1688 / eBay / Temu / Shopee / 其他' },
            { id: 'url', label: 'URL', type: 'url' },
            { id: 'isMain', label: '是否主推', type: 'switch' },
        ],
        help: '至少 1 条;主推渠道用于策略对齐',
        pdfSection: 'contact',
    },
    {
        id: 'node47_contacts',
        stage: 7, order: 44,
        label: '核心对接人及团队',
        component: 'dynamic-card',
        cardTemplate: [
            { id: 'name', label: '姓名', type: 'text' },
            { id: 'title', label: '职位', type: 'text' },
            { id: 'email', label: '邮箱', type: 'email' },
            { id: 'phone', label: '手机(含国际区号)', type: 'tel' },
            { id: 'whatsapp', label: 'WhatsApp', type: 'text' },
            { id: 'wechat', label: '微信', type: 'text' },
            { id: 'role', label: '角色', type: 'multi-select',
              options: ['项目主对接', '外贸业务员', '拍摄现场协调'] },
        ],
        help: '至少 1 名"项目主对接";外贸业务员可多人 — 用于 FB 询盘分流',
        pdfSection: 'contact',
    },
];

export function getField(id) {
    return FIELDS.find((f) => f.id === id);
}

export function fieldsByStage(stage) {
    return FIELDS.filter((f) => f.stage === stage).sort((a, b) => a.order - b.order);
}

export const TOTAL_FIELD_COUNT = FIELDS.length;
