// 46 节点完整字段 schema。
// 一份 schema 同时驱动:表单渲染 / 校验 / 联动 / PDF 输出 / ZIP 归档。
// 字段索引规则:`node{原节点排序}_{语义短名}`,与用户字段表节点排序一致。

export const FIELDS = [
    // ============ 阶段一:企业身份识别 ============
    {
        id: 'node1_companyNameZh',
        stage: 1, order: 1,
        label: '公司中文名称',
        required: true,
        component: 'text',
        placeholder: '例:广东创睿不锈钢有限公司(与营业执照完全一致)',
        validation: { min: 2, max: 50, mustContainAny: ['公司', '厂', '集团'] },
        pdfSection: 'identity', pdfKey: 'companyZh',
    },
    {
        id: 'node2_companyNameEn',
        stage: 1, order: 2,
        label: '公司英文名称',
        required: true,
        component: 'text',
        placeholder: '例:Guangdong Chuangrui Stainless Steel Co., Ltd.',
        validation: { min: 2, max: 80, pattern: /^[\x20-\x7E]+$/, patternMsg: '仅允许英文/数字/符号' },
        pdfSection: 'identity', pdfKey: 'companyEn',
    },
    {
        id: 'node3_brands',
        stage: 1, order: 3,
        label: '品牌名称(英文)',
        required: true,
        component: 'dynamic-list',
        itemLabel: '品牌',
        addLabel: '+ 添加备用品牌',
        min: 1, max: 8,
        itemField: { type: 'text', validation: { max: 30, pattern: /^[\x20-\x7E]+$/, patternMsg: '仅英文/数字' } },
        placeholder: '例:CHUANGRUI / T-CHEF',
        pdfSection: 'identity',
    },
    {
        id: 'node4_brandVisual',
        stage: 1, order: 4,
        label: '品牌视觉资产',
        required: true,
        component: 'composite',
        subFields: [
            { id: 'logo', label: 'Logo(透明背景矢量优先)', type: 'file',
              required: true, accept: ['ai', 'svg', 'png'], maxSize: 10 * 1024 * 1024 },
            { id: 'mainColor', label: '品牌主色(HEX)', type: 'color', required: true,
              validation: { pattern: /^#[0-9A-Fa-f]{6}$/, patternMsg: 'HEX 格式如 #C8102E' } },
            { id: 'sloganZh', label: 'Slogan 中文', type: 'text', required: true,
              placeholder: '例:源自源头·精于钢制' },
            { id: 'sloganEn', label: 'Slogan 英文', type: 'text', required: true,
              placeholder: '例:From the Mill, To the World' },
        ],
        help: '脚本字幕条、片头片尾必备素材',
        pdfSection: 'identity',
    },
    {
        id: 'node5_foundedYear',
        stage: 1, order: 5,
        label: '工厂成立年份',
        required: true,
        component: 'year',
        validation: { min: 1900, max: 2026 },
        pdfSection: 'identity', pdfKey: 'foundedYear',
    },
    {
        id: 'node6_license',
        stage: 1, order: 6,
        label: '营业执照',
        required: true,
        component: 'file',
        accept: ['pdf', 'jpg', 'png'],
        maxSize: 10 * 1024 * 1024,
        help: '立项表合规核验所需',
        pdfSection: 'identity',
    },
    {
        id: 'node8_address',
        stage: 1, order: 8,
        label: '公司及工厂地址',
        required: true,
        component: 'composite',
        subFields: [
            { id: 'region', label: '国-省-市-区', type: 'cascade-region', required: true },
            { id: 'addressZh', label: '详细地址(中文)', type: 'textarea', required: true,
              validation: { max: 100 } },
            { id: 'addressEn', label: '详细地址(英文)', type: 'textarea', required: true,
              validation: { max: 200 } },
            { id: 'sameAsRegistered', label: '注册地与生产地是否一致', type: 'radio',
              options: ['一致', '不一致'], required: true },
            { id: 'productionAddressZh', label: '生产地中文(若不一致)', type: 'textarea',
              showWhen: { field: 'sameAsRegistered', equals: '不一致' } },
            { id: 'productionAddressEn', label: '生产地英文(若不一致)', type: 'textarea',
              showWhen: { field: 'sameAsRegistered', equals: '不一致' } },
        ],
        pdfSection: 'identity',
    },

    // ============ 阶段二:规模与资质实力 ============
    {
        id: 'node9_employeeCount',
        stage: 2, order: 9,
        label: '员工总人数',
        required: true,
        component: 'select',
        options: ['1-50', '51-200', '201-500', '501-1000', '1000+'],
        help: '按当前在册全职员工总数',
        pdfSection: 'scale',
    },
    {
        id: 'node10_randTeam',
        stage: 2, order: 10,
        label: '研发团队人数及占比',
        required: true,
        component: 'composite',
        subFields: [
            { id: 'count', label: '研发人数', type: 'number', required: true,
              validation: { min: 0, integer: true } },
            { id: 'ratio', label: '占比(%)', type: 'slider',
              min: 0, max: 100, step: 1, required: true },
        ],
        help: '占比可由总员工数与研发数联动估算,需手动核对',
        pdfSection: 'scale',
    },
    {
        id: 'node11_plant',
        stage: 2, order: 11,
        label: '厂房面积',
        required: true,
        component: 'composite',
        subFields: [
            { id: 'area', label: '面积', type: 'number', required: true,
              validation: { min: 1 } },
            { id: 'unit', label: '单位', type: 'select', options: ['㎡', '亩'], required: true },
            { id: 'ownership', label: '产权', type: 'radio', options: ['自有', '租赁'], required: true },
            { id: 'aerialPhotos', label: '厂房航拍/外景图', type: 'file', multiple: true,
              required: true, accept: ['jpg', 'png'], maxSize: 20 * 1024 * 1024 },
        ],
        help: '航拍镜头与立项规模印证',
        pdfSection: 'scale',
    },
    {
        id: 'node12_honors',
        stage: 2, order: 12,
        label: '政府认定与行业荣誉',
        required: false,
        component: 'tag-multi-with-attachment',
        presetTags: ['国家高新技术企业', '专精特新', '省级出口优秀', '科技型中小企业'],
        customizable: true,
        itemFields: [
            { id: 'year', label: '颁发年份', type: 'year', required: true },
            { id: 'file', label: '证书扫描件', type: 'file', required: true,
              accept: ['pdf', 'jpg'], maxSize: 10 * 1024 * 1024 },
        ],
        help: '无则跳过;有则每项需附扫描件',
        pdfSection: 'qualifications',
    },
    {
        id: 'node13_certifications',
        stage: 2, order: 13,
        label: '企业资质与产品认证',
        required: true,
        component: 'cert-grid',
        presetTags: ['CE', 'RoHS', 'ISO9001', 'ISO14001', 'ISO45001', 'FDA', 'BSCI', 'ETL', 'NSF', 'FCC'],
        customizable: true,
        itemFields: [
            { id: 'issuer', label: '发证机构', type: 'text', required: true,
              placeholder: '如 TÜV / SGS / BV' },
            { id: 'certNo', label: '证书编号', type: 'text', required: true },
            { id: 'expiry', label: '有效期', type: 'date', required: true,
              validation: { afterToday: true } },
            { id: 'file', label: '证书扫描件', type: 'file', required: true,
              accept: ['pdf', 'jpg', 'png'], maxSize: 10 * 1024 * 1024 },
        ],
        help: '选中后展开补全三要素 + 扫描件',
        pdfSection: 'qualifications',
    },
    {
        id: 'node14_audits',
        stage: 2, order: 14,
        label: '大厂/第三方验厂授权',
        required: false,
        component: 'tag-multi-with-attachment',
        presetTags: ['SGS', 'BV', 'SMETA', '沃尔玛', '迪士尼', '亚马逊', 'Costco', 'IKEA'],
        customizable: true,
        itemFields: [
            { id: 'file', label: '报告/授权书', type: 'file', required: true,
              accept: ['pdf'], maxSize: 20 * 1024 * 1024 },
        ],
        pdfSection: 'qualifications',
    },

    // ============ 阶段三:生产能力画像 ============
    {
        id: 'node15_categories',
        stage: 3, order: 15,
        label: '主营产品类目',
        required: true,
        component: 'category-tree',
        validation: { minSelected: 1, leafLevel: 3 },
        help: '至少选择 1 项三级类目',
        pdfSection: 'capacity',
    },
    {
        id: 'node16_hsCodes',
        stage: 3, order: 16,
        label: '海关 HS 编码',
        required: true,
        component: 'dynamic-card',
        min: 1, max: 20,
        cardTemplate: [
            { id: 'code', label: 'HS 编码', type: 'text', required: true,
              validation: { pattern: /^\d{6}(\d{2})?(\d{2})?$/, patternMsg: 'HS 编码须为 6/8/10 位数字' } },
            { id: 'productName', label: '对应产品中文名', type: 'text', required: true },
            { id: 'isMain', label: '是否主推', type: 'switch' },
        ],
        help: '用于市场投放脚本筛选目标国',
        pdfSection: 'capacity',
    },
    {
        id: 'node17_catalog',
        stage: 3, order: 17,
        label: '产品电子图册(Catalog)',
        required: true,
        component: 'file',
        multiple: true,
        accept: ['pdf'],
        maxSize: 50 * 1024 * 1024,
        help: '完整产品手册 PDF;如有多套(中/英/分系列)请分别上传',
        pdfSection: 'capacity',
    },
    {
        id: 'node18_heroProducts',
        stage: 3, order: 18,
        label: '核心爆款/主推产品(3-5 款)',
        required: true,
        component: 'dynamic-card',
        min: 3, max: 5,
        cardTemplate: [
            { id: 'nameZh', label: '产品中文名', type: 'text', required: true },
            { id: 'nameEn', label: '产品英文名', type: 'text', required: true },
            { id: 'model', label: '型号', type: 'text', required: true },
            { id: 'specs', label: '关键参数(短文本)', type: 'textarea', required: true,
              validation: { max: 200 } },
            { id: 'priceMin', label: '批发价 USD 最低', type: 'number', required: true,
              validation: { min: 0 } },
            { id: 'priceMax', label: '批发价 USD 最高', type: 'number', required: true,
              validation: { min: 0 } },
            { id: 'priceUnit', label: '计价单位', type: 'select',
              options: ['pcs', 'sets', 'tons', '卷', 'm²'], required: true },
            { id: 'whiteBgPhoto', label: '白底图', type: 'file', required: true,
              accept: ['jpg', 'png'], maxSize: 20 * 1024 * 1024 },
            { id: 'scenePhoto', label: '场景图', type: 'file',
              accept: ['jpg', 'png'], maxSize: 20 * 1024 * 1024 },
            { id: 'mainMarket', label: '主推市场区域', type: 'select',
              options: ['北美', '欧洲', '中东', '东南亚', '南美', '非洲', '澳新', '独联体'],
              required: true },
        ],
        pdfSection: 'capacity',
    },
    {
        id: 'node19_productionLines',
        stage: 3, order: 19,
        label: '生产线分类与数量',
        required: true,
        component: 'dynamic-card',
        min: 1, max: 30,
        cardTemplate: [
            { id: 'name', label: '生产线名称', type: 'text', required: true,
              placeholder: '如:冷轧线 / 双机架平整退火炉' },
            { id: 'count', label: '数量', type: 'number', required: true,
              validation: { min: 1, integer: true } },
            { id: 'proprietary', label: '是否专有', type: 'switch' },
        ],
        pdfSection: 'capacity',
    },
    {
        id: 'node20_newModelsPerYear',
        stage: 3, order: 20,
        label: '每年新款开发数量',
        required: false,
        component: 'number',
        validation: { min: 0, integer: true },
        help: '纯定制行业可填 0 或不填',
        pdfSection: 'capacity',
    },
    {
        id: 'node21_hardPower',
        stage: 3, order: 21,
        label: '核心专有设备与工艺',
        required: true,
        component: 'dynamic-card',
        min: 1, max: 10,
        cardTemplate: [
            { id: 'name', label: '设备/工艺名称', type: 'text', required: true,
              placeholder: '如:十八辊八连轧' },
            { id: 'media', label: '照片或短视频', type: 'file', required: true,
              accept: ['jpg', 'png', 'mp4', 'mov'], maxSize: 200 * 1024 * 1024 },
            { id: 'advantage', label: '一句话优势', type: 'textarea', required: true,
              validation: { max: 80 } },
            { id: 'pioneer', label: '是否首创', type: 'radio',
              options: ['全球首创', '国内首创', '行业领先', '常规水平'], required: true },
        ],
        help: '脚本 VAR_HARD_POWER 核心来源',
        pdfSection: 'capacity',
    },
    {
        id: 'node22_supplyChain',
        stage: 3, order: 22,
        label: '供应链自主率',
        required: true,
        component: 'composite',
        subFields: [
            { id: 'level', label: '自主程度', type: 'radio',
              options: ['全产业链自产', '核心件自产', '组装加工'], required: true },
            { id: 'detail', label: '主要原材料来源与外采比例', type: 'textarea', required: true,
              validation: { max: 300 },
              placeholder: '例:钢坯自有 / 电机外采(占比 30%)' },
        ],
        pdfSection: 'capacity',
    },
    {
        id: 'node23_customization',
        stage: 3, order: 23,
        label: '定制服务能力(OEM/ODM)',
        required: true,
        component: 'composite',
        subFields: [
            { id: 'enabled', label: '是否提供定制', type: 'switch', required: true },
            { id: 'types', label: '定制类型', type: 'multi-select',
              options: ['OEM', 'ODM', 'JDM'],
              showWhen: { field: 'enabled', equals: true } },
            { id: 'leadTime', label: '定制周期', type: 'select',
              options: ['≤7 天', '8-15 天', '16-30 天', '30 天+'],
              showWhen: { field: 'enabled', equals: true } },
            { id: 'process', label: '定制流程描述', type: 'textarea',
              placeholder: '如:打样→确认→量产',
              showWhen: { field: 'enabled', equals: true } },
            { id: 'minMoq', label: '最小定制起订量', type: 'text',
              showWhen: { field: 'enabled', equals: true } },
        ],
        pdfSection: 'capacity',
    },

    // ============ 阶段四:品质与合规体系 ============
    {
        id: 'node24_qcWorkflow',
        stage: 4, order: 24,
        label: '质量管控体系(QC 流程)',
        required: true,
        component: 'composite',
        subFields: [
            { id: 'stages', label: '勾选实施环节', type: 'multi-select',
              options: ['IQC 进料检验', 'IPQC 过程检验', 'FQC 成品检验', 'OQC 出货检验', '可靠性测试'],
              required: true },
            { id: 'labPhotos', label: '实验室/检测设备照片', type: 'file', multiple: true,
              accept: ['jpg', 'png'], maxSize: 20 * 1024 * 1024, required: true },
            { id: 'coreItems', label: '核心检测项目', type: 'textarea', required: true,
              placeholder: '如:盐雾测试 96h / 拉伸强度 / 维氏硬度' },
        ],
        pdfSection: 'quality',
    },
    {
        id: 'node25_moq',
        stage: 4, order: 25,
        label: '起订量门槛(MOQ)',
        required: true,
        component: 'dynamic-card',
        min: 1, max: 20,
        cardTemplate: [
            { id: 'category', label: '产品类别', type: 'select', options: 'fromCategories', required: true },
            { id: 'qty', label: 'MOQ 数量', type: 'number', required: true,
              validation: { min: 0 } },
            { id: 'unit', label: '单位', type: 'select',
              options: ['pcs', 'sets', 'tons', '卷'], required: true },
            { id: 'note', label: '备注', type: 'text',
              placeholder: '如:可议 / 约 5 吨' },
        ],
        pdfSection: 'quality',
    },
    {
        id: 'node26_leadTime',
        stage: 4, order: 26,
        label: '交货周期(Lead Time)',
        required: true,
        component: 'composite',
        subFields: [
            { id: 'batch', label: '批量单平均天数', type: 'number', required: true,
              validation: { min: 1, integer: true } },
            { id: 'custom', label: '定制单平均天数', type: 'number', required: true,
              validation: { min: 1, integer: true } },
            { id: 'note', label: '备注(旺季加几天等)', type: 'text' },
        ],
        pdfSection: 'quality',
    },
    {
        id: 'node27_samplePolicy',
        stage: 4, order: 27,
        label: '样品政策',
        required: true,
        component: 'composite',
        subFields: [
            { id: 'cost', label: '样品费', type: 'radio',
              options: ['免费', '收费', '下单抵扣'], required: true },
            { id: 'freight', label: '运费', type: 'radio',
              options: ['买家付', '卖家付', '到付'], required: true },
            { id: 'amountUsd', label: '典型样品费(USD)', type: 'number',
              validation: { min: 0 } },
        ],
        pdfSection: 'quality',
    },
    {
        id: 'node28_workflow',
        stage: 4, order: 28,
        label: '企业内部业务流转',
        required: true,
        component: 'sortable-list',
        defaultItems: ['需求', '设计', '生产', '检测', '交付', '售后'],
        min: 3,
        editable: true,
        help: '直接驱动后续【生产流程↔取景区域】联动',
        pdfSection: 'quality',
    },

    // ============ 阶段五:市场与客户背景 ============
    {
        id: 'node29_marketMatrix',
        stage: 5, order: 29,
        label: '主推市场与产品线匹配',
        required: true,
        component: 'matrix-2d',
        rowsLabel: '市场区域',
        rowOptions: ['北美', '欧洲', '中东', '东南亚', '南美', '非洲', '澳新', '独联体'],
        colsLabel: '主推产品线',
        colSource: { field: 'node18_heroProducts', valueKey: 'nameZh' },
        cellField: { id: 'reason', label: '为什么推这个市场', type: 'textarea',
                     validation: { max: 200 } },
        validation: { minCells: 1 },
        help: '行选市场,列选产品,格内填理由;至少 1 对',
        pdfSection: 'market',
    },
    {
        id: 'node30_keywords',
        stage: 5, order: 30,
        label: '行业关键词清单',
        required: true,
        component: 'composite',
        subFields: [
            { id: 'zh', label: '中文标签', type: 'tag-input' },
            { id: 'en', label: '英文标签', type: 'tag-input', required: true,
              validation: { minItems: 10 } },
        ],
        help: '英文标签至少 10 个',
        pdfSection: 'market',
    },
    {
        id: 'node31_blacklist',
        stage: 5, order: 31,
        label: '不接单区域(黑名单)',
        required: false,
        component: 'dynamic-card',
        max: 30,
        cardTemplate: [
            { id: 'country', label: '国家/地区', type: 'country-select', required: true },
            { id: 'reason', label: '原因', type: 'select',
              options: ['合规', '物流', '无认证', '历史坏账', '其他'], required: true },
            { id: 'note', label: '备注', type: 'text' },
        ],
        pdfSection: 'market',
    },
    {
        id: 'node32_domesticCompetitors',
        stage: 5, order: 32,
        label: '国内同行业竞争对手',
        required: false,
        component: 'dynamic-card',
        max: 5,
        cardTemplate: [
            { id: 'name', label: '公司名称', type: 'text', required: true },
            { id: 'brand', label: '品牌', type: 'text' },
            { id: 'website', label: '官网 URL', type: 'url',
              validation: { url: true } },
            { id: 'social', label: '社媒账号链接', type: 'tag-input',
              placeholder: '回车添加 FB / IG / LinkedIn 链接' },
        ],
        pdfSection: 'market',
    },
    {
        id: 'node33_overseasCompetitors',
        stage: 5, order: 33,
        label: '国外同行业竞争对手',
        required: false,
        component: 'dynamic-card',
        max: 5,
        cardTemplate: [
            { id: 'name', label: '公司名称', type: 'text', required: true },
            { id: 'country', label: '所在国家', type: 'country-select', required: true },
            { id: 'website', label: '官网 URL', type: 'url',
              validation: { url: true } },
            { id: 'social', label: '海外社媒账号', type: 'tag-input',
              placeholder: '回车添加 FB / IG / YouTube / LinkedIn' },
        ],
        help: '便于内容对标分析',
        pdfSection: 'market',
    },
    {
        id: 'node34_customerCases',
        stage: 5, order: 34,
        label: '海外客户落地案例',
        required: false,
        component: 'dynamic-card',
        max: 5,
        cardTemplate: [
            { id: 'country', label: '客户所在国', type: 'country-select', required: true },
            { id: 'type', label: '客户类型', type: 'select',
              options: ['贸易商', '品牌商', '工厂'], required: true },
            { id: 'years', label: '合作年限', type: 'number',
              validation: { min: 0 } },
            { id: 'scenario', label: '典型订单场景', type: 'textarea',
              validation: { max: 300 } },
            { id: 'authorized', label: '是否可授权使用 LOGO/照片', type: 'radio',
              options: ['是', '否'], required: true },
            { id: 'photos', label: '现场照片', type: 'file', multiple: true,
              accept: ['jpg', 'png'], maxSize: 20 * 1024 * 1024 },
        ],
        help: '脚本"信任建立"类钩子素材源',
        pdfSection: 'market',
    },
    {
        id: 'node35_testimonials',
        stage: 5, order: 35,
        label: '高频复购原因(客户证言)',
        required: true,
        component: 'composite',
        subFields: [
            { id: 'reasons', label: '复购原因', type: 'multi-select',
              options: ['品质稳定', '交期准时', '价格优势', '响应快', '技术支持', '独家工艺'],
              required: true },
            { id: 'quotes', label: '客户原话', type: 'dynamic-card', required: true,
              min: 2,
              cardTemplate: [
                  { id: 'quoteZh', label: '原话中文', type: 'textarea', required: true },
                  { id: 'quoteEn', label: '英文翻译', type: 'textarea', required: true },
                  { id: 'country', label: '客户国家', type: 'country-select', required: true },
                  { id: 'allowName', label: '是否可署名', type: 'radio',
                    options: ['可署名', '匿名'], required: true },
                  { id: 'screenshot', label: '邮件/聊天截图', type: 'file', required: true,
                    accept: ['jpg', 'png'], maxSize: 20 * 1024 * 1024 },
              ],
            },
        ],
        help: '至少 2 条带截图的客户原话',
        pdfSection: 'market',
    },
    {
        id: 'node36_afterSales',
        stage: 5, order: 36,
        label: '售后保障服务',
        required: true,
        component: 'multi-select-with-detail',
        options: [
            { key: 'warranty', label: 'X 年质保', detailLabel: '具体年限' },
            { key: 'spareParts', label: '免费备件', detailLabel: '备件范围' },
            { key: 'support', label: '1V1 技术支持', detailLabel: '服务时段' },
            { key: 'overseasWarehouse', label: '海外仓换货', detailLabel: '覆盖区域' },
            { key: 'installation', label: '安装指导', detailLabel: '形式' },
            { key: 'video', label: '视频教学', detailLabel: '课程数量' },
        ],
        validation: { minSelected: 1 },
        pdfSection: 'market',
    },
    {
        id: 'node37_misconceptions',
        stage: 5, order: 37,
        label: '常见买家误解及纠偏',
        required: true,
        component: 'dynamic-card',
        min: 1, max: 5,
        cardTemplate: [
            { id: 'misunderstanding', label: '买家以为...', type: 'textarea', required: true,
              validation: { max: 200 } },
            { id: 'truth', label: '实际我们是...', type: 'textarea', required: true,
              validation: { max: 200 } },
        ],
        help: '脚本"认知反转"钩子源',
        pdfSection: 'market',
    },
    {
        id: 'node38_audience',
        stage: 5, order: 38,
        label: '目标客户画像与反向排雷',
        required: true,
        component: 'composite',
        subFields: [
            { id: 'idealType', label: '理想买家类型', type: 'multi-select',
              options: ['批发商', '品牌商', '工程项目', '连锁终端', 'C 端'], required: true },
            { id: 'idealVolume', label: '采购量级', type: 'select',
              options: ['<1 万 USD', '1-10 万 USD', '10-50 万 USD', '50 万+ USD'], required: true },
            { id: 'idealRole', label: '决策角色', type: 'multi-select',
              options: ['采购总监', '老板/创始人', '工程师', '产品经理', '渠道商'], required: true },
            { id: 'unwanted', label: '不理想客户(反向排雷)', type: 'textarea', required: true,
              validation: { max: 300 },
              placeholder: '如:单次 <MOQ 的零售试单' },
        ],
        pdfSection: 'market',
    },

    // ============ 阶段六:拍摄执行筹备 ============
    {
        id: 'node39_onCameraPeople',
        stage: 6, order: 39,
        label: '出镜人员筹备',
        required: true,
        component: 'dynamic-card',
        min: 1, max: 8,
        validation: { atLeastOneWith: { field: 'willing', equals: '必出镜' } },
        cardTemplate: [
            { id: 'name', label: '姓名', type: 'text', required: true },
            { id: 'title', label: '职位', type: 'text', required: true },
            { id: 'isFounder', label: '是否老板/创始人', type: 'switch' },
            { id: 'english', label: '是否能英文发言', type: 'radio',
              options: ['流利', '基本可以', '不可以'], required: true },
            { id: 'dress', label: '着装风格', type: 'select',
              options: ['西装', '工服', '便装'], required: true },
            { id: 'willing', label: '上镜意愿', type: 'radio',
              options: ['必出镜', '可出镜', '拒绝'], required: true },
        ],
        help: '至少 1 人愿意出镜;明确老板/创始人 — 信任背书最强镜头',
        pdfSection: 'shooting',
    },
    {
        id: 'node40_locations',
        stage: 6, order: 40,
        label: '核心取景区域及可拍摄清单',
        required: true,
        component: 'dynamic-card',
        min: 3, max: 20,
        cardTemplate: [
            { id: 'name', label: '区域名称', type: 'text', required: true },
            { id: 'photos', label: '区域照片', type: 'file', multiple: true, required: true,
              accept: ['jpg', 'png'], maxSize: 20 * 1024 * 1024 },
            { id: 'workflowNode', label: '对应业务流转节点', type: 'select',
              bindsTo: 'node28_workflow' },
            { id: 'aerial', label: '是否航拍可达', type: 'radio',
              options: ['是', '否'], required: true },
        ],
        pdfSection: 'shooting',
    },
    {
        id: 'node41_highlightShots',
        stage: 6, order: 41,
        label: '重点突出的高光镜头建议',
        required: false,
        component: 'composite',
        subFields: [
            { id: 'description', label: '镜头建议', type: 'textarea',
              validation: { max: 500 },
              placeholder: '如:突出十八辊轧机运转特写,体现极薄轧制实力' },
            { id: 'linkedLocations', label: '关联区域', type: 'multi-select',
              bindsTo: 'node40_locations', bindsToKey: 'name' },
            { id: 'linkedPains', label: '关联客户痛点', type: 'multi-select',
              bindsTo: ['node37_misconceptions', 'node38_audience'] },
        ],
        pdfSection: 'shooting',
    },
    {
        id: 'node42_existingAssets',
        stage: 6, order: 42,
        label: '现有素材库交接',
        required: false,
        component: 'dynamic-card',
        max: 20,
        cardTemplate: [
            { id: 'type', label: '素材类型', type: 'select',
              options: ['视频', '白底图', '场景图', '展会照', '客户来访照', '暂无'], required: true },
            { id: 'count', label: '数量', type: 'number',
              validation: { min: 0, integer: true } },
            { id: 'link', label: '云盘链接', type: 'url',
              validation: { url: true } },
            { id: 'extractCode', label: '提取码', type: 'text' },
            { id: 'authScope', label: '授权范围', type: 'multi-select',
              options: ['FB', 'IG', 'YouTube', '官网'] },
        ],
        pdfSection: 'shooting',
    },
    {
        id: 'node43_noShootZones',
        stage: 6, order: 43,
        label: '保密限制与禁拍区域',
        required: true,
        component: 'composite',
        subFields: [
            { id: 'warning', label: '保密事项(红字警示)', type: 'textarea', required: true,
              validation: { max: 500 },
              placeholder: '如:客户 LOGO 区 / 某型号模具 / 财务办公区' },
            { id: 'forbiddenLocations', label: '禁拍区域(从节点 40 取景区域勾选)',
              type: 'multi-select', bindsTo: 'node40_locations', bindsToKey: 'name' },
            { id: 'ndaFile', label: '保密协议(如需签署)', type: 'file',
              accept: ['pdf'], maxSize: 10 * 1024 * 1024 },
        ],
        pdfSection: 'shooting',
    },
    {
        id: 'node44_shootingSchedule',
        stage: 6, order: 44,
        label: '建议拍摄档期安排',
        required: true,
        component: 'composite',
        subFields: [
            { id: 'preferredFrom', label: '推荐窗口开始', type: 'date', required: true },
            { id: 'preferredTo', label: '推荐窗口结束', type: 'date', required: true,
              validation: { minRangeDays: { field: 'preferredFrom', days: 3 } } },
            { id: 'avoidFrom', label: '避开窗口开始', type: 'date' },
            { id: 'avoidTo', label: '避开窗口结束', type: 'date' },
            { id: 'workStart', label: '上班时间', type: 'time', required: true },
            { id: 'workEnd', label: '下班时间', type: 'time', required: true },
        ],
        help: '推荐窗口需至少 3 天',
        pdfSection: 'shooting',
    },
    {
        id: 'node45_languages',
        stage: 6, order: 45,
        label: '多语言版本需求',
        required: false,
        component: 'multi-select',
        options: ['英文(默认必选)', '西班牙文', '法文', '俄文', '阿拉伯文', '泰文', '越南文', '葡萄牙文'],
        defaultValue: ['英文(默认必选)'],
        pdfSection: 'shooting',
    },

    // ============ 阶段七:联络与数字化触点 ============
    {
        id: 'node46_platforms',
        stage: 7, order: 46,
        label: '现有电商/官网矩阵',
        required: true,
        component: 'dynamic-card',
        min: 1, max: 15,
        cardTemplate: [
            { id: 'platform', label: '平台', type: 'select',
              options: ['独立站', 'Alibaba', 'Made-in-China', 'Global Sources',
                        'Amazon', '1688', 'eBay', 'Temu', 'Shopee', '其他'],
              required: true },
            { id: 'url', label: 'URL', type: 'url', required: true,
              validation: { url: true } },
            { id: 'isMain', label: '是否主推', type: 'switch' },
        ],
        help: '至少 1 条;主推渠道用于策略对齐',
        pdfSection: 'contact',
    },
    {
        id: 'node47_contacts',
        stage: 7, order: 47,
        label: '核心对接人及团队',
        required: true,
        component: 'dynamic-card',
        min: 1, max: 10,
        validation: { atLeastOneWith: { field: 'role', includes: '项目主对接' } },
        cardTemplate: [
            { id: 'name', label: '姓名', type: 'text', required: true },
            { id: 'title', label: '职位', type: 'text', required: true },
            { id: 'email', label: '邮箱', type: 'email', required: true,
              validation: { email: true } },
            { id: 'phone', label: '手机(含国际区号)', type: 'tel', required: true,
              validation: { pattern: /^\+?\d[\d\s-]{6,20}$/, patternMsg: '请填含国际区号的电话' } },
            { id: 'whatsapp', label: 'WhatsApp', type: 'text' },
            { id: 'wechat', label: '微信', type: 'text' },
            { id: 'role', label: '角色', type: 'multi-select',
              options: ['项目主对接', '外贸业务员', '拍摄现场协调'], required: true },
        ],
        help: '至少 1 名"项目主对接";外贸业务员可多人 — 用于 FB 询盘分流',
        pdfSection: 'contact',
    },
];

export function getField(id) {
    return FIELDS.find((f) => f.id === id);
}

export function fieldsByStage(stage) {
    return FIELDS.filter((f) => f.stage === stage).sort((a, b) => a.order - b.order);
}

export const TOTAL_FIELD_COUNT = FIELDS.length;
